name: Generate Pac-Man Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: Ashutosh1510
          outputs: "github-contribution-grid-pacman.svg"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Pac-Man commit grid"
          branch: output
